### ISSUE TITLE
ValueError: Shape must be rank 4 but is rank 2 for 'Conv2D_2' (op: 'Conv2D') with input shapes: 

### ISSUE THREAD

**Issue by c1a1o1** [Vincentli8540/CS230_Project#1]
E:\Users\Raytine\Anaconda3\python.exe F:/zhaiyao/CS230-IcGAN-image-editing-tensorflow-master/main.py --OPER_FLAG 1 --celebA 1
Creating directory...
Path already exists.
Path already exists.
Path already exists.
Training celebA dataset:
(8192, 64, 64, 3)
z_var (64, 1, 1, 1024)
d1 (64, 4, 4, 512)
d5 (64, 64, 64, 3)
x (64, 64, 64, 3)
c1 (64, 32, 32, 32)
Traceback (most recent call last):
  File "E:\Users\Raytine\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1567, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 4 but is rank 2 for 'Conv2D_2' (op: 'Conv2D') with input shapes: [64,16,16,64], [32768,100].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/zhaiyao/CS230-IcGAN-image-editing-tensorflow-master/main.py", line 127, in <module>
    sample_path=sample_path , log_dir = log_dir , gen_learning_rate=gen_learn_rate, dis_learning_rate=dis_learn_rate , info_reg_coeff=1.0)
  File "F:\zhaiyao\CS230-IcGAN-image-editing-tensorflow-master\Gan_celebA.py", line 54, in __init__
    self.build_model2()
  File "F:\zhaiyao\CS230-IcGAN-image-editing-tensorflow-master\Gan_celebA.py", line 97, in build_model2
    self.e_z= self.encode_z(self.fake_images, weights=self.weights3, biases=self.biases3)
  File "F:\zhaiyao\CS230-IcGAN-image-editing-tensorflow-master\Gan_celebA.py", line 456, in encode_z
    c3 = tf.nn.relu(batch_normal(conv2d(c2, weights['e3'], biases['eb3']), scope='enz_bn3'))
  File "F:\zhaiyao\CS230-IcGAN-image-editing-tensorflow-master\ops.py", line 11, in conv2d
    x = tf.nn.conv2d(x , W , strides=[1, strides , strides, 1], padding= padding_)
  File "E:\Users\Raytine\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1042, in conv2d
c2 (64, 16, 16, 64)
    data_format=data_format, dilations=dilations, name=name)
  File "E:\Users\Raytine\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "E:\Users\Raytine\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3392, in create_op
    op_def=op_def)
  File "E:\Users\Raytine\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1734, in __init__
    control_input_ops)
  File "E:\Users\Raytine\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: Shape must be rank 4 but is rank 2 for 'Conv2D_2' (op: 'Conv2D') with input shapes: [64,16,16,64], [32768,100].

**Comment by jyj0309** [comment]
have you solved this issue?
